### ISSUE TITLE
Скласти додаткові інформаційні блоки:

### ISSUE THREAD

**Issue by vverzun** [vverzun/homepage#10]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by merkulovsa** [comment]
### ― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.

**Comment by merkulovsa** [comment]
#### LANGUAGES
:us: ENGLISH :cn: MANDARIN :jp: JAPANESE

#### SKILLS  

KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS

#### CHARACTER  

NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE

#### LIFE LESSON
You must defeat Sheng Long to stand a chance.

#### LIKES :smiley:  

GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY

#### DISLIKES :disappointed:  

BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES

#### WANTS 🥺
BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY

**Comment by vverzun** [comment]
![](https://media.tenor.com/images/f1a791b4774a32f7aaf18b13cb7c5f7b/tenor.gif)
