### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by vverzun** [vverzun/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо

**Comment by personalCollaborator** [comment]
― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.

**Comment by merkulovsa** [comment]
### ― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.

**Comment by vverzun** [comment]
![](https://media.tenor.com/images/f1a791b4774a32f7aaf18b13cb7c5f7b/tenor.gif)
